version: '3.8'
services:
  remote-schedule-service:
    image: melowetty/remote-schedule-service
    env_file: ./.env
    environment:
      - SPRING_PROFILES_ACTIVE=$ACTIVE_PROFILE
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://$SERVICE_DISCOVERY_USER:$SERVICE_DISCOVERY_PASSWORD@$SERVICE_DISCOVERY_HOST:$SERVICE_DISCOVERY_PORT/eureka
    restart: always
    networks:
      - service-discovery_internal
networks:
  service-discovery_internal:
    external: true
