version: '3.8'
services:
  remote-schedule-service:
    image: melowetty/remote-schedule-service
    container_name: remote-schedule-service
    env_file: .env
    environment:
      - SPRING_PROFILES_ACTIVE=$ACTIVE_PROFILE
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:$POSTGRESDB_DOCKER_PORT/$DB_NAME
      - SPRING_DATASOURCE_USERNAME=$DB_USERNAME
      - SPRING_DATASOURCE_PASSWORD=$DB_PASSWORD
    restart: always
    networks:
      - api-gateway_backend
      - internal
    expose:
      - $SERVER_PORT
  postgresdb:
    image: postgres
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
    networks:
      - internal
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
networks:
  internal:
  api-gateway_backend:
    external: true
