name: Tests and build

on:
  pull_request:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
        
      - name: Build
        run: ./gradlew build
        
      - name: Test
        run: ./gradlew check

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-gradle-output
          path: |
            build/libs/remote-schedule-service-standalone.jar
          retention-days: 1

  push_to_registry:
    name: Deploy New Version
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7

        with:
          images: melowetty/remote-schedule-service

      - name: Download Jar
        uses: actions/download-artifact@v4
        with:
          name: build-gradle-output

      - name: Log in to Docker Hub
        uses: docker/login-action@40891eba8c2bcd1309b07ba8b11232f313e86779
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Image
        uses: docker/build-push-action@eafaea8d0f5853934deece2ffa67af59d936562b
        with:
          context: .
          push: true
          tags: melowetty/remote-schedule-service:latest
          labels: ${{ steps.meta.outputs.labels }}
